#!/bin/sh /etc/rc.common

#
# Modemguard
# V1.2
#
# Disables Teltonika modems when they're not needed.
#
# Copyright 2021 James M Dabbs III
# Distributed under the Boost Software License, Version 1.0.
# See https://www.boost.org/LICENSE_1_0.txt
#

USE_PROCD=1
NAME=mgd
PROG=/usr/sbin/mg
START=99
STOP=10

stop_service() {
 /usr/sbin/mg stop
}

start_service() {
 procd_open_instance [instance_name]
 procd_set_param command /usr/sbin/mg run
 procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
 procd_set_param limits core="unlimited"
 procd_set_param file /var/etc/mg.conf
 procd_set_param stdout 1
 procd_set_param stderr 1
 procd_set_param pidfile /var/run/mg.pid
 procd_close_instance
}

